"""
origin/engine.py — AI Origin Estimate Engine v5.0

Computes three-way probability distribution for code origin:
  - p_fully_ai_generated: code likely generated by AI in one shot
  - p_ai_assisted: code likely created with AI assistance (Copilot-like)
  - p_human_authored: code likely written by hand without AI tools

IMPORTANT: These are heuristic probability estimates, NOT forensic proof.
Never interpret as confirmed AI authorship.

Methodology:
  1. Map adjusted_score to base probability mixture using overlapping functions
  2. Apply modifiers: scaffold completeness, prompt residue, human irregularity,
     style continuity, magic number discipline, category context, framework context
  3. Normalize to sum to 1.0
  4. Build OriginEstimate with confidence and interval
"""
from __future__ import annotations

from typing import List, Optional, Tuple

from ..domain import FileCategory, FrameworkContext, OriginEstimate
from ..origin.confidence import ConfidenceInterval, compute_interval


# ── Base probability functions ─────────────────────────────────────────────────
# Each function maps adjusted_score ∈ [0, 1] → raw component weight ∈ [0, 1].
# Components are overlapping — they are normalised to sum to 1.0 after modifiers.

def _base_fully_ai(score: float) -> float:
    """Peaks for high scores (> 0.55). Linear ramp from 0.40 → 1.0."""
    return max(0.0, (score - 0.40) / 0.40)


def _base_ai_assisted(score: float) -> float:
    """Peaks in the medium range (0.35–0.55). Triangle centred at 0.45."""
    return max(0.0, 1.0 - abs(score - 0.45) / 0.28)


def _base_human_authored(score: float) -> float:
    """Peaks for low scores (< 0.35). Linear ramp down from 0.55 → 0."""
    return max(0.0, (0.55 - score) / 0.55)


# ── Modifier helpers ───────────────────────────────────────────────────────────

def _clamp(value: float, lo: float = 0.0, hi: float = 1.0) -> float:
    """Clamp a float to [lo, hi]."""
    return max(lo, min(hi, value))


def _prompt_residue_from_signals(signals: dict) -> float:
    """Extract prompt_residue signal from a FileAnalysis signals dict."""
    return float(signals.get("prompt_residue", 0.0))


def _human_irregularity_from_signals(signals: dict) -> float:
    """
    Derive human-irregularity proxy from existing signals.

    Combines: empty_catch (inverted), bare_except (not in signals directly,
    approximated via exception_style inverted), and placeholder_density.
    High irregularity → human signal.
    """
    empty_catch = signals.get("empty_catch", 0.5)
    exception_style = signals.get("exception_style", 0.5)
    placeholder = signals.get("placeholder_density", 0.0)

    # empty_catch high = absence of empty catch = AI-like → invert for human signal
    human_empty_catch = 1.0 - _clamp(empty_catch)
    # exception_style high = disciplined = AI-like → invert for human signal
    human_exception = 1.0 - _clamp(exception_style)
    # placeholder_density high = human residue (TODOs, etc.)
    human_placeholder = _clamp(placeholder)

    irregularity = (human_empty_catch * 0.35 + human_exception * 0.35
                    + human_placeholder * 0.30)
    return _clamp(irregularity)


# ── Confidence derivation ──────────────────────────────────────────────────────

def _derive_confidence(confidence_level: float) -> str:
    """Map numeric confidence [0, 1] to a 'low' | 'medium' | 'high' label."""
    if confidence_level >= 0.70:
        return "high"
    if confidence_level >= 0.50:
        return "medium"
    return "low"


# ── Driver generation ──────────────────────────────────────────────────────────

def _build_drivers(
    adjusted_score: float,
    scaffold_score: float,
    prompt_residue: float,
    style_continuity: float,
    human_irregularity: float,
    magic_number_score: float,
    name_body_coherence: float,
    category: FileCategory,
    framework_ctx: Optional[FrameworkContext],
) -> List[str]:
    """Return up to 3 human-readable driver strings explaining the estimate."""
    candidates: List[Tuple[float, str]] = []

    # Score-based drivers
    if adjusted_score >= 0.65:
        candidates.append((adjusted_score, "High adjusted pattern score — strong AI-like signals"))
    elif adjusted_score >= 0.45:
        candidates.append((adjusted_score, "Moderate adjusted pattern score — mixed signals"))
    else:
        candidates.append((1.0 - adjusted_score, "Low adjusted pattern score — human-like signals"))

    # Scaffold completeness
    if scaffold_score >= 0.70:
        candidates.append((scaffold_score, f"High scaffold completeness ({scaffold_score:.2f}) — uniform, symmetrical structure"))
    elif scaffold_score <= 0.25:
        candidates.append((1.0 - scaffold_score, f"Low scaffold completeness ({scaffold_score:.2f}) — irregular structure"))

    # Prompt residue
    if prompt_residue >= 0.50:
        candidates.append((prompt_residue, f"Prompt residue detected ({prompt_residue:.2f}) — LLM-like explanatory language"))

    # Style continuity
    if style_continuity <= 0.55:
        candidates.append((1.0 - style_continuity, f"Style discontinuity ({style_continuity:.2f}) — suggests partial AI editing"))
    elif style_continuity >= 0.85:
        candidates.append((style_continuity * 0.5, f"High style continuity ({style_continuity:.2f}) — uniform style throughout"))

    # Human irregularity
    if human_irregularity >= 0.55:
        candidates.append((human_irregularity, f"Human irregularity signals ({human_irregularity:.2f}) — error handling or naming inconsistency"))

    # Magic number discipline
    if magic_number_score >= 0.65:
        candidates.append((magic_number_score * 0.7, f"High magic-number discipline ({magic_number_score:.2f}) — constants used consistently"))
    elif magic_number_score <= 0.20:
        candidates.append((1.0 - magic_number_score, f"Low magic-number discipline ({magic_number_score:.2f}) — many unnamed literals"))

    # Name-body coherence
    if name_body_coherence >= 0.70:
        candidates.append((name_body_coherence * 0.6, f"High name-body coherence ({name_body_coherence:.2f}) — descriptive naming matches implementation"))

    # Category context
    if category == FileCategory.GENERATED:
        candidates.append((0.9, "File classified as generated — excluded from AI-origin KPI"))
    elif category == FileCategory.DTO_MAPPER:
        candidates.append((0.6, "DTO/mapper category — inherently regular; score adjusted downward"))
    elif category == FileCategory.TEST:
        candidates.append((0.5, "Test file — AI-assisted test generation is common"))

    # Framework context
    if framework_ctx and framework_ctx.is_framework_boilerplate:
        candidates.append((0.55, "Framework boilerplate detected — structural patterns are framework-driven"))

    # Sort by priority and return top 3
    candidates.sort(key=lambda x: -x[0])
    return [desc for _, desc in candidates[:3]]


def _build_uncertainty_reasons(
    confidence_level: float,
    adjusted_score: float,
    lines: int,
    has_git: bool,
    category: FileCategory,
) -> List[str]:
    """Return uncertainty reasons for the origin estimate."""
    reasons: List[str] = []

    if confidence_level < 0.50:
        reasons.append(
            f"Low signal confidence ({confidence_level:.2f}) — signals point in conflicting directions"
        )

    if lines < 30:
        reasons.append("Very small file (< 30 lines) — insufficient evidence for reliable estimate")
    elif lines < 60:
        reasons.append("Small file (< 60 lines) — limited signal coverage")

    if not has_git:
        reasons.append("No git history — temporal signals unavailable")

    if 0.40 <= adjusted_score <= 0.55:
        reasons.append(
            f"Adjusted score ({adjusted_score:.2f}) falls in ambiguous range [0.40–0.55] "
            "— all three categories overlap here"
        )

    if category == FileCategory.DTO_MAPPER:
        reasons.append(
            "DTO/mapper files inherently score high on regularity — origin estimate less reliable"
        )
    elif category == FileCategory.GENERATED:
        reasons.append(
            "Auto-generated files always appear AI-like — origin estimate is not meaningful"
        )

    return reasons


# ── Main computation ───────────────────────────────────────────────────────────

def compute_file_origin(
    file_analysis: object,
    scaffold_score: float = 0.0,
    style_continuity: float = 1.0,
    magic_number_score: float = 0.5,
    name_body_coherence: float = 0.5,
) -> OriginEstimate:
    """
    Compute a three-way origin probability estimate for a single file.

    Args:
        file_analysis:      A ``FileAnalysis`` instance (scoring/model.py).
                            Must have: adjusted_score, confidence, signals,
                            category, framework_context, lines.
        scaffold_score:     Scaffold completeness signal in [0, 1].
                            Higher = more uniform/symmetric structure.
        style_continuity:   Style continuity score in [0, 1].
                            1.0 = perfectly continuous, 0.0 = maximum discontinuity.
        magic_number_score: Magic-number discipline signal in [0, 1].
                            Higher = fewer magic numbers = more disciplined.
        name_body_coherence: Name-to-body coherence signal in [0, 1].
                            Higher = names align with implementation.

    Returns:
        OriginEstimate with three-way percentages summing to 100.
    """
    # -- Extract attributes from FileAnalysis --
    adjusted_score: float = getattr(file_analysis, "adjusted_score", 0.40)
    confidence_level: float = getattr(file_analysis, "confidence", 0.50)
    signals: dict = getattr(file_analysis, "signals", {})
    category: FileCategory = getattr(file_analysis, "category", FileCategory.UNKNOWN)
    framework_ctx: Optional[FrameworkContext] = getattr(file_analysis, "framework_context", None)
    lines: int = getattr(file_analysis, "lines", 0)
    has_git: bool = bool(getattr(file_analysis, "module_path", None) is not None)  # proxy

    adjusted_score = _clamp(adjusted_score)
    confidence_level = _clamp(confidence_level)
    scaffold_score = _clamp(scaffold_score)
    style_continuity = _clamp(style_continuity)
    magic_number_score = _clamp(magic_number_score)
    name_body_coherence = _clamp(name_body_coherence)

    # -- Step 1: Base probability mixture from overlapping functions --
    p_ai = _base_fully_ai(adjusted_score)
    p_assist = _base_ai_assisted(adjusted_score)
    p_human = _base_human_authored(adjusted_score)

    # -- Step 2: Apply modifiers (small, ±0.05–0.20 max) --

    # 2a. Scaffold completeness → boosts fully_ai
    if scaffold_score >= 0.70:
        boost = (scaffold_score - 0.70) / 0.30 * 0.15   # up to +0.15
        p_ai += boost

    # 2b. Prompt residue → boosts fully_ai
    prompt_residue = _prompt_residue_from_signals(signals)
    if prompt_residue >= 0.40:
        p_ai += (prompt_residue - 0.40) / 0.60 * 0.12   # up to +0.12

    # 2c. Style discontinuity → boosts ai_assisted
    style_discontinuity = 1.0 - style_continuity
    if style_discontinuity >= 0.30:
        boost = (style_discontinuity - 0.30) / 0.70 * 0.15   # up to +0.15
        p_assist += boost
        p_ai -= boost * 0.5   # partial shift from fully_ai to ai_assisted

    # 2d. Human irregularity → boosts human_authored
    human_irregularity = _human_irregularity_from_signals(signals)
    if human_irregularity >= 0.40:
        boost = (human_irregularity - 0.40) / 0.60 * 0.18   # up to +0.18
        p_human += boost

    # 2e. High magic-number discipline → small boost to fully_ai (disciplined = AI-like)
    if magic_number_score >= 0.65:
        p_ai += (magic_number_score - 0.65) / 0.35 * 0.06   # up to +0.06

    # Low magic-number discipline → small boost to human (messy = human-like)
    elif magic_number_score <= 0.25:
        p_human += (0.25 - magic_number_score) / 0.25 * 0.06   # up to +0.06

    # 2f. Name-body coherence → small boost to fully_ai
    if name_body_coherence >= 0.70:
        p_ai += (name_body_coherence - 0.70) / 0.30 * 0.07   # up to +0.07

    # 2g. Category modifiers
    if category == FileCategory.GENERATED:
        # Generated code is excluded from KPI but always looks AI-like
        p_ai += 0.20
        p_human -= 0.10

    elif category == FileCategory.DTO_MAPPER:
        # DTOs look AI-like by nature, but it's framework/tooling, not LLM
        p_ai -= 0.10
        p_assist += 0.10

    elif category == FileCategory.TEST:
        # Tests are frequently AI-assisted (Copilot completions)
        p_assist += 0.08
        p_ai -= 0.04

    elif category == FileCategory.VENDOR:
        # Vendor code is not AI-generated; it's third-party
        p_human += 0.15
        p_ai -= 0.10

    # 2h. Framework context → reduces fully_ai signal
    if framework_ctx and framework_ctx.is_framework_boilerplate:
        reduction = min(0.12, framework_ctx.boilerplate_score * 0.15)
        p_ai -= reduction
        p_assist += reduction * 0.5

    # -- Step 3: Clamp all components to non-negative before normalisation --
    p_ai = max(0.0, p_ai)
    p_assist = max(0.0, p_assist)
    p_human = max(0.0, p_human)

    # -- Step 4: Normalise to sum to 1.0 --
    total = p_ai + p_assist + p_human
    if total < 1e-9:
        # Degenerate case: equal split
        p_ai, p_assist, p_human = 1.0 / 3, 1.0 / 3, 1.0 / 3
        total = 1.0

    p_ai /= total
    p_assist /= total
    p_human /= total

    # Convert to percentage space
    fully_ai_pct = p_ai * 100.0
    ai_assist_pct = p_assist * 100.0
    human_pct = p_human * 100.0

    # -- Step 5: Confidence --
    confidence_label = _derive_confidence(confidence_level)

    # Data quality proxy: does FileAnalysis have non-trivial signals?
    active_signals = sum(1 for v in signals.values() if v > 0.0)
    data_quality = min(1.0, active_signals / 10.0)

    # Build confidence intervals for each component
    fully_ai_interval = compute_interval(fully_ai_pct, confidence_level, data_quality)
    ai_assist_interval = compute_interval(ai_assist_pct, confidence_level, data_quality)
    human_interval = compute_interval(human_pct, confidence_level, data_quality)

    # -- Step 6: Drivers and uncertainty reasons --
    drivers = _build_drivers(
        adjusted_score=adjusted_score,
        scaffold_score=scaffold_score,
        prompt_residue=prompt_residue,
        style_continuity=style_continuity,
        human_irregularity=human_irregularity,
        magic_number_score=magic_number_score,
        name_body_coherence=name_body_coherence,
        category=category,
        framework_ctx=framework_ctx,
    )

    uncertainty_reasons = _build_uncertainty_reasons(
        confidence_level=confidence_level,
        adjusted_score=adjusted_score,
        lines=lines,
        has_git=has_git,
        category=category,
    )

    return OriginEstimate(
        fully_ai_generated_pct=round(fully_ai_pct, 2),
        ai_assisted_pct=round(ai_assist_pct, 2),
        human_authored_pct=round(human_pct, 2),
        confidence=confidence_label,
        confidence_level=round(confidence_level, 4),
        intervals={
            "fully_ai_generated": fully_ai_interval,
            "ai_assisted": ai_assist_interval,
            "human_authored": human_interval,
        },
        drivers=drivers,
        uncertainty_reasons=uncertainty_reasons,
    )


# ── Portfolio aggregation ──────────────────────────────────────────────────────

def aggregate_origin_estimates(
    estimates_with_loc: List[Tuple[OriginEstimate, int]],
) -> OriginEstimate:
    """
    Aggregate multiple file-level OriginEstimates into a portfolio-level estimate.

    Each estimate is weighted by lines-of-code (LOC). This ensures that large
    files have proportionally more influence on the portfolio result.

    Args:
        estimates_with_loc: List of (OriginEstimate, loc) pairs.
                            LOC must be > 0; zero-LOC entries are skipped.

    Returns:
        A single OriginEstimate representing the portfolio. If the input list
        is empty, returns an equal-split estimate with low confidence.
    """
    from ..origin.confidence import portfolio_interval

    valid = [(est, loc) for est, loc in estimates_with_loc if loc > 0]

    if not valid:
        # Return a neutral equal-split estimate
        return OriginEstimate(
            fully_ai_generated_pct=33.3,
            ai_assisted_pct=33.3,
            human_authored_pct=33.4,
            confidence="low",
            confidence_level=0.0,
            drivers=["No files analysed — estimate is neutral placeholder"],
            uncertainty_reasons=["No files provided for aggregation"],
        )

    total_loc = sum(loc for _, loc in valid)
    weighted_ai = 0.0
    weighted_assist = 0.0
    weighted_human = 0.0
    weighted_confidence = 0.0

    for est, loc in valid:
        weight = loc / total_loc
        weighted_ai += est.fully_ai_generated_pct * weight
        weighted_assist += est.ai_assisted_pct * weight
        weighted_human += est.human_authored_pct * weight
        weighted_confidence += est.confidence_level * weight

    # Renormalise percentages to exactly 100
    pct_total = weighted_ai + weighted_assist + weighted_human
    if pct_total > 0:
        scale = 100.0 / pct_total
        weighted_ai *= scale
        weighted_assist *= scale
        weighted_human *= scale

    avg_confidence = _clamp(weighted_confidence)
    confidence_label = _derive_confidence(avg_confidence)
    n_files = len(valid)

    # Portfolio intervals are wider than single-file intervals (heuristic)
    # but narrow as the number of files grows
    ai_interval = portfolio_interval(weighted_ai, n_repos=n_files, avg_confidence=avg_confidence)
    assist_interval = portfolio_interval(weighted_assist, n_repos=n_files, avg_confidence=avg_confidence)
    human_interval = portfolio_interval(weighted_human, n_repos=n_files, avg_confidence=avg_confidence)

    drivers = [
        f"Portfolio of {n_files} files weighted by lines-of-code",
        f"Weighted average confidence: {avg_confidence:.2f}",
        f"Total analysed LOC: {total_loc:,}",
    ]

    uncertainty_reasons: List[str] = []
    if n_files < 5:
        uncertainty_reasons.append(
            f"Only {n_files} file(s) — portfolio estimate has high variance"
        )
    if avg_confidence < 0.50:
        uncertainty_reasons.append(
            f"Average confidence is low ({avg_confidence:.2f}) — individual file estimates are unreliable"
        )

    return OriginEstimate(
        fully_ai_generated_pct=round(weighted_ai, 2),
        ai_assisted_pct=round(weighted_assist, 2),
        human_authored_pct=round(weighted_human, 2),
        confidence=confidence_label,
        confidence_level=round(avg_confidence, 4),
        intervals={
            "fully_ai_generated": ai_interval,
            "ai_assisted": assist_interval,
            "human_authored": human_interval,
        },
        drivers=drivers,
        uncertainty_reasons=uncertainty_reasons,
    )
