"""
scanners/filesystem.py — File discovery, classification, and filtering.

Classifies each file as: production | test | generated | vendor | unsupported.
Only production and (optionally) test files are analyzed.
"""
from __future__ import annotations
import re
from dataclasses import dataclass
from enum import Enum, auto
from pathlib import Path
from typing import Generator, Optional

from ..config import EXTENSION_TO_LANG, MAX_FILE_BYTES, MIN_LINES, SKIP_DIRS


class FileKind(Enum):
    PRODUCTION  = auto()
    TEST        = auto()
    GENERATED   = auto()
    VENDOR      = auto()
    UNSUPPORTED = auto()


@dataclass(frozen=True)
class DiscoveredFile:
    path: Path
    language: str
    kind: FileKind
    size_bytes: int

    @property
    def is_scannable(self) -> bool:
        return self.kind in (FileKind.PRODUCTION, FileKind.TEST)


_GENERATED_NAME_RE = re.compile(
    r"(_pb2|_pb2_grpc|_grpc|\.generated\.|Generated|swagger|openapi"
    r"|\.min\.|\.bundle\.|\.chunk\.|migration_\d{4}|schema_auto)", re.I,
)
_GENERATED_HEADER_RE = re.compile(
    r"(?://|#|/\*|<!--)\s*"
    r"(?:Code generated|DO NOT EDIT|Auto-generated|Generated by|"
    r"automatically generated|@generated|@auto-generated)", re.I,
)

_TEST_NAME_RE = re.compile(
    r"(?:^|[_\-\.])(?:test|tests|spec|specs|mock|fixture|benchmark)(?:[_\-\.]|$)"
    r"|(?:Test|Spec|Mock|Fixture|Benchmark)s?\.", re.I,
)
_TEST_DIR_RE  = re.compile(
    r"(?:^|[\\/])(?:tests?|specs?|__tests__|benchmarks?)(?:[\\/]|$)", re.I
)
_TEST_CONTENT_RE = re.compile(
    r"\bimport\s+pytest\b|@pytest\.mark|unittest\.TestCase"
    r"|@Test\b|@BeforeEach|@AfterEach|@RunWith"
    r"|\bdescribe\s*\(|it\s*\(\s*['\"]|expect\s*\("
    r"|func\s+Test[A-Z]\w+\s*\(t\s+\*testing",
)
_VENDOR_DIR_RE = re.compile(
    r"(?:^|[\\/])(?:vendor|third.?party|thirdparty|extern|external"
    r"|bower_components|jspm_packages)(?:[\\/]|$)", re.I,
)


def _is_generated(path: Path, header: str) -> bool:
    if _GENERATED_NAME_RE.search(path.name):
        return True
    if _GENERATED_HEADER_RE.search(header):
        return True
    lines = header.splitlines()
    if lines and (sum(len(l) for l in lines) / len(lines)) > 400:
        return True
    return False


def _is_test(path: Path, header: str) -> bool:
    if _TEST_NAME_RE.search(path.name):
        return True
    if _TEST_DIR_RE.search(str(path)):
        return True
    return bool(_TEST_CONTENT_RE.search(header))


def classify_file(path: Path) -> Optional[DiscoveredFile]:
    """Classify a single file. Returns None if the file should be skipped."""
    lang = EXTENSION_TO_LANG.get(path.suffix.lower())
    if not lang:
        return None
    try:
        stat = path.stat()
    except OSError:
        return None
    if stat.st_size == 0 or stat.st_size > MAX_FILE_BYTES:
        return None
    try:
        raw    = path.read_bytes()
        header = raw[:2048].decode("utf-8", errors="ignore")
    except OSError:
        return None
    if raw.count(b"\n") + 1 < MIN_LINES:
        return None

    if _VENDOR_DIR_RE.search(str(path)):
        kind = FileKind.VENDOR
    elif _is_generated(path, header):
        kind = FileKind.GENERATED
    elif _is_test(path, header):
        kind = FileKind.TEST
    else:
        kind = FileKind.PRODUCTION

    return DiscoveredFile(path=path, language=lang, kind=kind, size_bytes=stat.st_size)


def walk_repo(root: Path, include_tests: bool = True) -> Generator[DiscoveredFile, None, None]:
    """Walk a repo without following symlinks. Yields scannable DiscoveredFiles."""
    try:
        entries = list(root.iterdir())
    except (PermissionError, OSError):
        return
    for entry in entries:
        if entry.name in SKIP_DIRS:
            continue
        if entry.is_symlink():
            continue
        if entry.is_dir():
            yield from walk_repo(entry, include_tests=include_tests)
        elif entry.is_file():
            df = classify_file(entry)
            if df is None or df.kind in (FileKind.VENDOR, FileKind.GENERATED):
                continue
            if df.kind == FileKind.TEST and not include_tests:
                continue
            yield df
