"""
scanners/filesystem.py — File discovery, classification, and filtering.

v4.0: Extended with FileCategory (semantic classification) in addition to
      the legacy FileKind (structural kind). FileCategory is used for score
      adjustment; FileKind is kept for backward compatibility.

v5.0: Significantly extended vendor/generated path detection patterns.
      Added iOS (Pods, Carthage), Python (site-packages), proto/grpc/avro/swagger,
      and kapt/apt generated sources. Updated SKIP_DIRS accordingly.

File category classification order (first match wins):
  1. Vendor/third-party directory check
  2. Generated code (headers, patterns, path-based)
  3. Migration scripts (Flyway, Alembic, Liquibase patterns)
  4. Example/tutorial code (examples/, demos/, tutorial/ folders)
  5. Config/infrastructure (application.yml, pom.xml, build.gradle, etc.)
  6. DTO/mapper classification (name patterns + content signals)
  7. Test files (content, path, name patterns)
  8. Notebook (.ipynb)
  9. Framework integration boilerplate (Spring @Configuration, etc.)
  10. Production logic (default)

⚠ Classification is heuristic; some files may be misclassified.
   Category is reported in output so false classifications can be identified.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from enum import Enum, auto
from pathlib import Path
from typing import Generator, Optional

from ..config import EXTENSION_TO_LANG, MAX_FILE_BYTES, MIN_LINES, SKIP_DIRS
from ..domain import FileCategory


# ── Legacy FileKind (kept for backward compatibility) ─────────────────────────

class FileKind(Enum):
    PRODUCTION  = auto()
    TEST        = auto()
    GENERATED   = auto()
    VENDOR      = auto()
    UNSUPPORTED = auto()


# ── Discovered file ───────────────────────────────────────────────────────────

@dataclass(frozen=True)
class DiscoveredFile:
    path: Path
    language: str
    kind: FileKind                    # legacy
    category: FileCategory            # v4.0 semantic category
    size_bytes: int
    module_path: str = ""             # relative module path for grouping

    @property
    def is_scannable(self) -> bool:
        return self.kind not in (FileKind.VENDOR, FileKind.UNSUPPORTED)

    @property
    def is_kpi_eligible(self) -> bool:
        """Files that count toward the AI-adoption KPI."""
        return self.category not in (
            FileCategory.GENERATED,
            FileCategory.VENDOR,
            FileCategory.EXAMPLE,
        )


# ── Generated code patterns ───────────────────────────────────────────────────

_GENERATED_NAME_RE = re.compile(
    r"(_pb2|_pb2_grpc|_grpc|\.generated\.|Generated|swagger|openapi"
    r"|\.min\.|\.bundle\.|\.chunk\.|migration_\d{4}|schema_auto"
    r"|AutoGenerated|_gen\.|generated_|\.pb\.go|jooq)", re.I,
)
_GENERATED_HEADER_RE = re.compile(
    r"(?://|#|/\*|<!--)\s*"
    r"(?:Code generated|DO NOT EDIT|Auto-generated|Generated by|"
    r"automatically generated|@generated|@auto-generated|"
    r"This file was automatically|This code is auto-generated)", re.I,
)

# v5.0: Comprehensive generated code directory patterns
_GENERATED_DIR_RE = re.compile(
    r"(?:^|[\\/])(?:"
    r"generated|gen|__generated__|auto\.?generated|"
    r"generated[\-_]sources?|target[\\/]generated|"
    r"build[\\/]generated|generated[\-_]out|"
    r"openapi|swagger|avro|protobuf|proto|grpc|"
    r"graphql[\-_]generated|jooq[\-_]generated|thrift|"
    r"\.generated|annotation[\-_]processing|"
    r"apt[\-_]generated|kapt[\-_]generated"
    r")(?:[\\/]|$)", re.I,
)
_OPENAPI_GENERATED_RE = re.compile(
    r"@Schema\s*\(|@ApiModel\b|openapi-generator|swagger-codegen", re.I,
)


def _is_generated(path: Path, header: str) -> bool:
    if _GENERATED_NAME_RE.search(path.name):
        return True
    if _GENERATED_DIR_RE.search(str(path)):
        return True
    if _GENERATED_HEADER_RE.search(header):
        return True
    lines = header.splitlines()
    if lines and len(lines) >= 3:
        avg_len = sum(len(l) for l in lines[:20]) / max(len(lines[:20]), 1)
        if avg_len > 400:
            return True
    return False


# ── Test file patterns ────────────────────────────────────────────────────────

_TEST_NAME_RE = re.compile(
    r"(?:^|[_\-\.])(?:test|tests|spec|specs|mock|fixture|benchmark)(?:[_\-\.]|$)"
    r"|(?:Test|Spec|Mock|Fixture|Benchmark)s?\.",
    re.I,
)
_TEST_DIR_RE = re.compile(
    r"(?:^|[\\/])(?:tests?|specs?|__tests__|benchmarks?|test_?)(?:[\\/]|$)", re.I,
)
_TEST_CONTENT_RE = re.compile(
    r"\bimport\s+pytest\b|@pytest\.mark|unittest\.TestCase"
    r"|@Test\b|@BeforeEach|@AfterEach|@RunWith|@ExtendWith"
    r"|\bdescribe\s*\(|it\s*\(\s*['\"]|expect\s*\("
    r"|func\s+Test[A-Z]\w+\s*\(t\s+\*testing"
    r"|class\s+\w+Test\s*\(|class\s+Test\w+\(",
)


def _is_test(path: Path, header: str, root: Optional[Path] = None) -> bool:
    if _TEST_NAME_RE.search(path.name):
        return True
    # Use relative path for directory check to avoid matching parent dirs like /Documents/Tests/
    check_path = str(path.relative_to(root)) if root else str(path)
    if _TEST_DIR_RE.search(check_path):
        return True
    return bool(_TEST_CONTENT_RE.search(header))


# ── Vendor patterns ───────────────────────────────────────────────────────────

# v5.0: Comprehensive vendor/third-party directory patterns
_VENDOR_DIR_RE = re.compile(
    r"(?:^|[\\/])(?:"
    r"vendor|vendored|third.?party|thirdparty|external|"
    r"extern|deps|dependencies|libs?|bower_components|"
    r"node_modules|jspm_packages|__vendor__|"
    r"org\.apache|com\.google|io\.netty|"        # common package structures inside vendored dirs
    r"site[\-_]packages|dist[\-_]packages|"      # Python vendored
    r"Pods|Carthage|Frameworks"                  # iOS vendored
    r")(?:[\\/]|$)", re.I,
)


# ── Migration patterns ────────────────────────────────────────────────────────

_MIGRATION_NAME_RE = re.compile(
    r"(?:V\d+__[\w_]+|R__[\w_]+|B\d+__[\w_]+|"       # Flyway
    r"\d{4}\d{2}\d{2}\d{4,}_\w+|"                     # Alembic timestamp
    r"migration_\d+|migrate_\d+|upgrade_\d+|"
    r"changelog\.\d+|db_migration)", re.I,
)
_MIGRATION_DIR_RE = re.compile(
    r"(?:^|[\\/])(?:migrations?|db[-_]migrations?|flyway|"
    r"liquibase|alembic|schema[-_]changes?)(?:[\\/]|$)", re.I,
)
_MIGRATION_CONTENT_RE = re.compile(
    r"CREATE\s+TABLE|ALTER\s+TABLE|DROP\s+TABLE|"
    r"def\s+upgrade\s*\(\s*\)|def\s+downgrade\s*\(\s*\)|"
    r"op\.create_table|op\.add_column|"
    r"<changeSet\s|databaseChangeLog", re.I,
)


def _is_migration(path: Path, header: str) -> bool:
    if _MIGRATION_NAME_RE.search(path.stem):
        return True
    if _MIGRATION_DIR_RE.search(str(path)):
        return True
    if _MIGRATION_CONTENT_RE.search(header):
        return True
    return False


# ── Example/tutorial patterns ─────────────────────────────────────────────────

_EXAMPLE_DIR_RE = re.compile(
    r"(?:^|[\\/])(?:examples?|demos?|tutorials?|samples?|"
    r"playground|showcase|getting[-_]started)(?:[\\/]|$)", re.I,
)
_EXAMPLE_NAME_RE = re.compile(
    r"example[-_]|[-_]example|demo[-_]|[-_]demo|sample[-_]|[-_]sample|"
    r"tutorial[-_]|[-_]tutorial|playground", re.I,
)


def _is_example(path: Path) -> bool:
    return bool(_EXAMPLE_DIR_RE.search(str(path)) or _EXAMPLE_NAME_RE.search(path.stem))


# ── Config / infrastructure patterns ─────────────────────────────────────────

_CONFIG_NAMES = frozenset({
    "application.yml", "application.yaml", "application.properties",
    "application-dev.yml", "application-prod.yml", "application-test.yml",
    "bootstrap.yml", "bootstrap.yaml",
    "pom.xml", "build.gradle", "build.gradle.kts", "settings.gradle",
    "pyproject.toml", "setup.py", "setup.cfg", "requirements.txt",
    "Pipfile", "poetry.lock", "Pipfile.lock",
    "docker-compose.yml", "docker-compose.yaml", "Dockerfile",
    ".env", ".env.example", ".env.template",
    "logback.xml", "logback-spring.xml", "log4j2.xml",
    "checkstyle.xml", "pmd.xml", "spotbugs-exclude.xml",
    ".pylintrc", "mypy.ini", ".flake8", "pyproject.toml", "ruff.toml",
    "Makefile", "makefile",
    "sonar-project.properties",
})

_CONFIG_EXTENSIONS = frozenset({".yml", ".yaml", ".xml", ".properties", ".toml", ".ini", ".cfg"})

_CONFIG_DIR_RE = re.compile(
    r"(?:^|[\\/])(?:config|configuration|infra|infrastructure|"
    r"helm|k8s|kubernetes|terraform|ansible|ci)(?:[\\/]|$)", re.I,
)


def _is_config(path: Path) -> bool:
    if path.name.lower() in _CONFIG_NAMES:
        return True
    if path.suffix.lower() in _CONFIG_EXTENSIONS:
        return True
    if _CONFIG_DIR_RE.search(str(path)):
        return True
    return False


# ── DTO / mapper patterns ─────────────────────────────────────────────────────

_DTO_NAME_RE = re.compile(
    r"(?:Dto|DTO|Request|Response|Payload|View|VO|"
    r"Command|Event|Message|Transfer|Model|Entity|Schema|"
    r"Mapper|Converter|Transformer)\b",
)

_MAPPER_NAME_RE = re.compile(
    r"(?:Mapper|Converter|Transformer|Assembler|Builder)\b",
)


def _is_dto_or_mapper(path: Path, header: str, lang: str) -> bool:
    name = path.stem
    if _DTO_NAME_RE.search(name):
        return True
    # Check content for @Entity, @Data, Pydantic BaseModel, etc.
    if lang in ("Java", "Kotlin"):
        if re.search(r"@(?:Entity|Data|Value|Embeddable|MappedSuperclass)\b", header):
            return True
        if re.search(r"class\s+\w+(?:DTO|Dto|Request|Response|Payload)\b", header):
            return True
    elif lang == "Python":
        if re.search(r"class\s+\w+\(\s*(?:BaseModel|Schema|TypedDict)\s*\)", header):
            return True
    return False


def _is_mapper(path: Path) -> bool:
    return bool(_MAPPER_NAME_RE.search(path.stem))


# ── Framework boilerplate patterns ────────────────────────────────────────────

_FRAMEWORK_BOILERPLATE_RE = re.compile(
    r"@(?:SpringBootApplication|EnableWebMvc|EnableAutoConfiguration|"
    r"Configuration|EnableJpaRepositories|EnableCaching|"
    r"EnableScheduling|EnableAsync|EnableWebSecurity|"
    r"ComponentScan|PropertySource|MapperScan)\b",
)


def _is_framework_boilerplate(header: str, lang: str) -> bool:
    if lang not in ("Java", "Kotlin"):
        return False
    return bool(_FRAMEWORK_BOILERPLATE_RE.search(header))


# ── Temporary script patterns ─────────────────────────────────────────────────

_TEMP_SCRIPT_DIR_RE = re.compile(
    r"(?:^|[\\/])(?:tmp|temp|scratch|one[-_]off|quick[-_]fix|"
    r"utility[-_]script|admin[-_]script|data[-_]fix)(?:[\\/]|$)", re.I,
)
_TEMP_STEM_RE = re.compile(
    r"^(?:tmp[-_]|temp[-_]|scratch[-_]|one[-_]off|quick[-_]fix|"
    r"fix[-_]\w+|patch[-_]\w+|data[-_]fix|migrate[-_]once|one[-_]time[-_])\w*$",
    re.I,
)


def _is_temp_script(path: Path) -> bool:
    if _TEMP_SCRIPT_DIR_RE.search(str(path.parent)):
        return True
    # Only match clearly temp-named files (with separator after tmp/temp)
    return bool(_TEMP_STEM_RE.match(path.stem))


# ── Master classifier ─────────────────────────────────────────────────────────

def determine_category(path: Path, header: str, lang: str, kind: FileKind) -> FileCategory:
    """
    Determine the semantic FileCategory for a file.
    Classification order is significant — first match wins.

    v5.0: Vendor and generated path detection is applied aggressively using
    the extended _VENDOR_DIR_RE and _GENERATED_DIR_RE patterns even when
    FileKind does not indicate vendor/generated, to catch vendored code that
    sits outside the canonical vendor/ directory.
    """
    # v5.0: Apply vendor dir regex aggressively — catches vendored code
    # in unusual locations (e.g. libs/, Pods/, site-packages/)
    if kind == FileKind.VENDOR or _VENDOR_DIR_RE.search(str(path)):
        return FileCategory.VENDOR

    # v5.0: Apply generated dir regex aggressively — catches proto/grpc/avro outputs
    if kind == FileKind.GENERATED or _is_generated(path, header) or _GENERATED_DIR_RE.search(str(path)):
        return FileCategory.GENERATED

    # Test detection before other patterns (test files take priority)
    if kind == FileKind.TEST:
        return FileCategory.TEST

    if _is_migration(path, header):
        return FileCategory.MIGRATION

    if _is_example(path):
        return FileCategory.EXAMPLE

    if path.suffix.lower() == ".ipynb":
        return FileCategory.NOTEBOOK

    if _is_config(path) and lang not in ("Python", "Java", "Kotlin", "TypeScript"):
        return FileCategory.CONFIG_INFRA

    if _is_temp_script(path):
        return FileCategory.CONFIG_INFRA  # treat as infra/utility

    if _is_dto_or_mapper(path, header, lang):
        return FileCategory.DTO_MAPPER

    if _is_mapper(path):
        return FileCategory.DTO_MAPPER

    if _is_framework_boilerplate(header, lang):
        return FileCategory.BOILERPLATE_INTEG

    return FileCategory.PRODUCTION_LOGIC


# ── Module path extraction ─────────────────────────────────────────────────────

def extract_module_path(path: Path, root: Path) -> str:
    """
    Extract a relative module path from a file path relative to repo root.
    Used for module-level aggregation in reports.
    """
    try:
        rel = path.relative_to(root)
        parts = rel.parts
        # Use package path (directory structure), not filename
        if len(parts) > 1:
            return "/".join(parts[:-1])
        return ""
    except ValueError:
        return ""


# ── Main classifier ───────────────────────────────────────────────────────────

def classify_file(path: Path, root: Optional[Path] = None) -> Optional[DiscoveredFile]:
    """Classify a single file. Returns None if the file should be skipped."""
    lang = EXTENSION_TO_LANG.get(path.suffix.lower())
    if not lang:
        return None
    try:
        stat = path.stat()
    except OSError:
        return None
    if stat.st_size == 0 or stat.st_size > MAX_FILE_BYTES:
        return None
    try:
        raw    = path.read_bytes()
        header = raw[:2048].decode("utf-8", errors="ignore")
    except OSError:
        return None
    if raw.count(b"\n") + 1 < MIN_LINES:
        return None

    # Determine legacy FileKind
    if _VENDOR_DIR_RE.search(str(path)):
        kind = FileKind.VENDOR
    elif _is_generated(path, header):
        kind = FileKind.GENERATED
    elif _is_test(path, header, root=root):
        kind = FileKind.TEST
    else:
        kind = FileKind.PRODUCTION

    # Determine semantic FileCategory
    category = determine_category(path, header, lang, kind)

    # Module path
    module_path = extract_module_path(path, root) if root else ""

    return DiscoveredFile(
        path=path,
        language=lang,
        kind=kind,
        category=category,
        size_bytes=stat.st_size,
        module_path=module_path,
    )


def walk_repo(
    root: Path,
    include_tests: bool = True,
    ignored_paths: Optional[list] = None,
) -> Generator[DiscoveredFile, None, None]:
    """
    Walk a repository without following symlinks. Yields scannable DiscoveredFiles.
    Respects SKIP_DIRS and optional ignored_paths patterns.
    """
    ignored_patterns = [re.compile(p, re.I) for p in (ignored_paths or [])]

    def _walk(current: Path) -> Generator[DiscoveredFile, None, None]:
        try:
            entries = list(current.iterdir())
        except (PermissionError, OSError):
            return
        for entry in entries:
            if entry.name in SKIP_DIRS:
                continue
            if entry.is_symlink():
                continue
            # Check ignored patterns
            rel_str = str(entry)
            if any(p.search(rel_str) for p in ignored_patterns):
                continue
            if entry.is_dir():
                yield from _walk(entry)
            elif entry.is_file():
                df = classify_file(entry, root=root)
                if df is None:
                    continue
                if df.kind == FileKind.VENDOR:
                    continue
                if df.kind == FileKind.TEST and not include_tests:
                    continue
                yield df

    yield from _walk(root)
