"""
tests/test_vendor_paths.py — Tests for vendor/generated path detection (v5.0).

Requirements:
  - vendored/org/apache/commons/* → VENDOR
  - target/generated-sources/openapi/* → GENERATED
  - src/main/java/com/company/BillingService.java → PRODUCTION_LOGIC
  - proto/ paths → GENERATED or SKIP
  - Pods/ → VENDOR
"""
import sys, os, tempfile
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from pathlib import Path
from ai_pattern_analyzer.scanners.filesystem import (
    classify_file, _is_generated, _VENDOR_DIR_RE, _GENERATED_DIR_RE,
    FileCategory,
)


def _make_file(content: str, suffix: str = ".java") -> Path:
    f = tempfile.NamedTemporaryFile(mode="w", suffix=suffix, delete=False)
    f.write(content)
    f.flush()
    return Path(f.name)


# ── Regex-level tests (no real files needed) ──────────────────────────────────

def test_vendored_apache_commons_matches_vendor_regex():
    path = "app/src/full/java/vendored/org/apache/commons/DigestUtils.java"
    assert _VENDOR_DIR_RE.search(path), f"Should match vendor: {path}"

def test_vendored_hex_matches_vendor_regex():
    path = "app/src/full/java/vendored/org/apache/commons/Hex.java"
    assert _VENDOR_DIR_RE.search(path), f"Should match vendor: {path}"

def test_third_party_matches_vendor_regex():
    path = "src/third-party/json/Parser.java"
    assert _VENDOR_DIR_RE.search(path), f"Should match vendor: {path}"

def test_node_modules_matches_vendor_regex():
    path = "frontend/node_modules/lodash/index.js"
    assert _VENDOR_DIR_RE.search(path), f"Should match vendor: {path}"

def test_deps_matches_vendor_regex():
    path = "libs/deps/some-lib/Main.java"
    assert _VENDOR_DIR_RE.search(path), f"Should match vendor: {path}"

def test_pods_ios_matches_vendor_regex():
    path = "ios/Pods/Firebase/FirebaseCore.swift"
    assert _VENDOR_DIR_RE.search(path), f"Should match vendor: {path}"

def test_production_code_not_vendor():
    path = "src/main/java/com/company/BillingService.java"
    assert not _VENDOR_DIR_RE.search(path), f"Should NOT match vendor: {path}"

def test_generated_openapi_matches():
    path = "target/generated-sources/openapi/ApiClient.java"
    assert _GENERATED_DIR_RE.search(path), f"Should match generated: {path}"

def test_generated_grpc_matches():
    path = "src/generated/grpc/ServiceGrpc.java"
    assert _GENERATED_DIR_RE.search(path), f"Should match generated: {path}"

def test_generated_proto_matches():
    path = "src/main/proto/service.proto"
    assert _GENERATED_DIR_RE.search(path), f"Should match generated: {path}"

def test_generated_avro_matches():
    path = "src/main/avro/schema/Event.avsc"
    assert _GENERATED_DIR_RE.search(path), f"Should match generated: {path}"

def test_kapt_generated_matches():
    path = "build/generated/kapt/debug/com/example/DaggerComponent.java"
    assert _GENERATED_DIR_RE.search(path), f"Should match generated: {path}"

def test_production_src_not_generated():
    path = "src/main/java/com/company/service/OrderService.java"
    assert not _GENERATED_DIR_RE.search(path), f"Should NOT match generated: {path}"

def test_generated_name_pb2():
    path = "/repo/src/user_pb2.py"
    from ai_pattern_analyzer.scanners.filesystem import _GENERATED_NAME_RE
    assert _GENERATED_NAME_RE.search(Path(path).name), "pb2 should be generated"


# ── classify_file integration tests ──────────────────────────────────────────

MIN_CONTENT = "x = 1\n" * 15  # enough lines to pass MIN_LINES

def test_regular_python_classified_production():
    code = ("def calculate_billing(amount, tax_rate):\n"
            "    return amount * (1 + tax_rate)\n") * 8
    path = _make_file(code, suffix=".py")
    df = classify_file(path)
    assert df is not None
    assert df.category == FileCategory.PRODUCTION_LOGIC

def test_generated_header_classified_generated():
    code = "# Code generated by protoc. DO NOT EDIT.\n" + MIN_CONTENT
    path = _make_file(code, suffix=".py")
    df = classify_file(path)
    assert df is not None
    assert df.category == FileCategory.GENERATED

def test_do_not_edit_header_classified_generated():
    code = "// Auto-generated. DO NOT EDIT.\n" + "public class Stub {}\n" * 12
    path = _make_file(code, suffix=".java")
    df = classify_file(path)
    assert df is not None
    assert df.category == FileCategory.GENERATED


# ── KPI eligibility ───────────────────────────────────────────────────────────

def test_vendor_not_kpi_eligible():
    """Vendor files must be excluded from KPI by default."""
    from ai_pattern_analyzer.scanners.filesystem import DiscoveredFile, FileKind
    df = DiscoveredFile(
        path=Path("/repo/vendor/lib.py"),
        language="Python",
        kind=FileKind.VENDOR,
        category=FileCategory.VENDOR,
        size_bytes=1000,
    )
    assert not df.is_kpi_eligible

def test_generated_not_kpi_eligible():
    from ai_pattern_analyzer.scanners.filesystem import DiscoveredFile, FileKind
    df = DiscoveredFile(
        path=Path("/repo/generated/Client.java"),
        language="Java",
        kind=FileKind.GENERATED,
        category=FileCategory.GENERATED,
        size_bytes=5000,
    )
    assert not df.is_kpi_eligible

def test_production_is_kpi_eligible():
    from ai_pattern_analyzer.scanners.filesystem import DiscoveredFile, FileKind
    df = DiscoveredFile(
        path=Path("/repo/src/Service.java"),
        language="Java",
        kind=FileKind.PRODUCTION,
        category=FileCategory.PRODUCTION_LOGIC,
        size_bytes=3000,
    )
    assert df.is_kpi_eligible


if __name__ == "__main__":
    import traceback
    tests = [v for k, v in globals().items() if k.startswith("test_") and callable(v)]
    passed = failed = 0
    for t in tests:
        try:
            t()
            passed += 1
        except Exception as e:
            print(f"FAIL {t.__name__}: {e}")
            traceback.print_exc()
            failed += 1
    print(f"\n{passed} passed, {failed} failed")
