"""
tests/test_classification.py — Tests for file classification (FileCategory).
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

import tempfile
from pathlib import Path
from ai_pattern_analyzer.scanners.filesystem import (
    classify_file, determine_category, FileKind, FileCategory
)


def _tmp_file(content: str, suffix: str = ".py") -> Path:
    """Create a temporary file with given content."""
    f = tempfile.NamedTemporaryFile(mode="w", suffix=suffix, delete=False)
    f.write(content)
    f.flush()
    return Path(f.name)


# ── Generated code detection ──────────────────────────────────────────────────

def test_generated_header_detected():
    path = _tmp_file("# Code generated by protoc-gen-python. DO NOT EDIT.\n" + "x = 1\n" * 15)
    df = classify_file(path)
    assert df is not None
    assert df.category == FileCategory.GENERATED

def test_generated_name_detected():
    path = _tmp_file("x = 1\n" * 15, suffix="_pb2.py")
    df = classify_file(path)
    assert df is not None
    assert df.category == FileCategory.GENERATED

# ── Test file detection ───────────────────────────────────────────────────────

def test_test_by_name():
    path = _tmp_file("def test_something():\n    assert 1 == 1\n" * 10, suffix="_test.py")
    df = classify_file(path)
    assert df is not None
    assert df.category == FileCategory.TEST

def test_test_by_content():
    code = "import pytest\n\ndef test_foo():\n    assert True\n" + "x = 1\n" * 12
    path = _tmp_file(code, suffix=".py")
    df = classify_file(path)
    assert df is not None
    assert df.category == FileCategory.TEST

# ── DTO / Mapper detection ────────────────────────────────────────────────────

def test_dto_by_name():
    code = "from pydantic import BaseModel\nclass UserDto(BaseModel):\n    name: str\n    email: str\n" * 4
    path = _tmp_file(code, suffix="Dto.py")
    df = classify_file(path)
    assert df is not None
    assert df.category == FileCategory.DTO_MAPPER

def test_pydantic_base_model_is_dto():
    code = (
        "from pydantic import BaseModel\n"
        "class OrderRequest(BaseModel):\n"
        "    customer_id: str\n"
        "    items: list\n"
        "    address: str\n"
    ) * 4
    path = _tmp_file(code, suffix=".py")
    df = classify_file(path)
    assert df is not None
    assert df.category == FileCategory.DTO_MAPPER

# ── Production logic is default ───────────────────────────────────────────────

def test_production_logic_default():
    code = (
        "class OrderService:\n"
        "    def process(self, order):\n"
        "        if order.is_valid():\n"
        "            return self.repo.save(order)\n"
        "        return None\n"
    ) * 4
    path = _tmp_file(code, suffix=".py")
    df = classify_file(path)
    assert df is not None
    assert df.category == FileCategory.PRODUCTION_LOGIC

# ── Small file skipped ────────────────────────────────────────────────────────

def test_small_file_skipped():
    path = _tmp_file("x = 1\n", suffix=".py")
    df = classify_file(path)
    assert df is None  # too small (< MIN_LINES)

# ── Unknown extension not classified ─────────────────────────────────────────

def test_unknown_extension_skipped():
    path = _tmp_file("content\n" * 20, suffix=".xyz")
    df = classify_file(path)
    assert df is None  # unsupported extension


# ── Module path ───────────────────────────────────────────────────────────────

def test_module_path_extracted():
    from ai_pattern_analyzer.scanners.filesystem import extract_module_path
    root = Path("/repo")
    path = Path("/repo/src/main/java/com/example/service/OrderService.java")
    mp = extract_module_path(path, root)
    assert "src" in mp
    assert "service" in mp


if __name__ == "__main__":
    import traceback
    tests = [v for k, v in globals().items() if k.startswith("test_") and callable(v)]
    passed = failed = 0
    for t in tests:
        try:
            t()
            passed += 1
        except Exception as e:
            print(f"FAIL {t.__name__}: {e}")
            traceback.print_exc()
            failed += 1
    print(f"\n{passed} passed, {failed} failed")
