"""
reporting/markdown.py — Markdown report generation.

Generates human-readable Markdown reports suitable for:
  - Engineering leadership summaries
  - GitHub/GitLab PR comments
  - Wiki pages and documentation

Report sections:
  1. Executive summary
  2. Repository score breakdown
  3. Category breakdown (production logic vs DTOs vs tests)
  4. Module heatmap (top modules by adjusted score)
  5. High-risk file candidates for review
  6. Key findings and drivers
  7. Limitations and uncertainty
  8. Review checklist (generated from findings)

Extension point: HTML report can be generated by wrapping this output
in HTML with a CSS framework.
"""
from __future__ import annotations

import datetime
from pathlib import Path
from typing import Dict, List, Optional

from ..scoring.calibration import RepoStats
from ..scoring.model import FileAnalysis
from ..config import ANALYZER_VERSION, SCORING_MODEL_VERSION


DISCLAIMER_MD = (
    "> ⚠ **Important:** This report detects code-style and structural patterns that are "
    "statistically correlated with AI-assisted or mechanically generated code. "
    "It does **not** prove AI authorship, does not identify code origin, and must **not** "
    "be used as evidence for personnel decisions, compliance claims, or legal assertions. "
    "Results are probabilistic pattern indicators only."
)


def _score_bar(score: float, width: int = 20) -> str:
    filled = int(score * width)
    return "█" * filled + "░" * max(0, width - filled)


def _score_emoji(score: float) -> str:
    if score >= 0.65:
        return "🔴"
    if score >= 0.45:
        return "🟡"
    return "🟢"


def _band_label(score: float) -> str:
    if score >= 0.75:
        return "HIGH"
    if score >= 0.50:
        return "ELEVATED"
    if score >= 0.25:
        return "MODERATE"
    return "LOW"


def build_markdown_report(
    all_stats: List[RepoStats],
    all_analyses: Dict[str, List[FileAnalysis]],
    scan_config: Optional[object] = None,
) -> str:
    """Build a complete Markdown report for all scanned repositories."""
    lines = []
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    lines += [
        "# Code Engineering Pattern Analyzer — Report",
        f"",
        f"**Generated:** {now}  ",
        f"**Analyzer version:** {ANALYZER_VERSION}  ",
        f"**Scoring model:** {SCORING_MODEL_VERSION}  ",
        f"",
        DISCLAIMER_MD,
        f"",
        "---",
        "",
    ]

    # Executive summary table
    lines += [
        "## Executive Summary",
        "",
        "| Repository | KPI Score | AI-like% | Files | Risk | Pattern |",
        "|---|---|---|---|---|---|",
    ]
    for stats in sorted(all_stats, key=lambda s: -s.kpi_score):
        emoji = _score_emoji(stats.kpi_score)
        kpi_pct = f"{stats.kpi_score * 100:.1f}%"
        ai_pct  = f"{stats.ai_like_pct:.1f}%"
        risk_lvl = "High" if stats.mean_risk >= 0.50 else ("Moderate" if stats.mean_risk >= 0.30 else "Low")
        lines.append(
            f"| {stats.repo_name} | {emoji} {kpi_pct} | {ai_pct} | "
            f"{stats.production_files} | {risk_lvl} | {stats.summary_label} |"
        )
    lines += ["", "---", ""]

    # Per-repository detail
    for stats in all_stats:
        analyses = all_analyses.get(stats.repo_name, [])
        lines += _build_repo_section(stats, analyses)
        lines += ["", "---", ""]

    # Methodology note
    lines += [
        "## Methodology",
        "",
        "This report uses heuristic analysis of source code patterns. "
        "Scores reflect **AI-like coding patterns** (regularity, structural uniformity, "
        "comment density, type annotation coverage, naming conventions) — not verified AI origin.",
        "",
        "**Score bands:**",
        "- 🟢 0–25%: Low — patterns consistent with typical hand-written code",
        "- 🟡 26–50%: Moderate — may reflect tooling, framework conventions, or clean-code standards",
        "- 🟡 51–75%: Elevated — warrants contextual review",
        "- 🔴 76–100%: High — strong AI-like or generated-like characteristics",
        "",
        "**Adjusted score** accounts for file category (DTOs, mappers, generated code) and "
        "framework context (Spring, JPA, Pydantic, MapStruct). "
        "**Risk score** reflects engineering review priority, not AI-likeness alone.",
        "",
        "**Recommended use:** Repository-level trends, team-level adoption proxy, "
        "changed-code monitoring, manual review prioritization.",
        "",
        "**Not recommended:** Individual developer evaluation, contractual AI-contribution claims, "
        "legal/forensic classification.",
    ]

    return "\n".join(lines)


def _build_repo_section(stats: RepoStats, analyses: List[FileAnalysis]) -> List[str]:
    lines = []
    emoji = _score_emoji(stats.kpi_score)

    lines += [
        f"## {emoji} Repository: `{stats.repo_name}`",
        f"",
        f"**Summary:** {stats.summary_label}",
        f"",
        f"| Metric | Value |",
        f"|---|---|",
        f"| AI-Adoption KPI Score | {stats.kpi_score * 100:.1f}% ({_band_label(stats.kpi_score)}) |",
        f"| Adjusted Score (median) | {stats.median_adjusted * 100:.1f}% |",
        f"| Raw Likelihood (median) | {stats.median_likelihood * 100:.1f}% |",
        f"| Production files | {stats.production_files} |",
        f"| Test files | {stats.test_files} |",
        f"| Generated files excluded | {stats.generated_files} |",
        f"| High-risk files | {stats.high_risk_count} |",
        f"| Data quality score | {stats.data_quality_score * 100:.0f}% |",
        f"",
    ]

    # Category breakdown
    if stats.category_summaries:
        lines += [
            "### Category Breakdown",
            "",
            "| Category | Files | Adj. Score | Confidence |",
            "|---|---|---|---|",
        ]
        for cat in stats.category_summaries:
            lines.append(
                f"| {cat.category} | {cat.file_count} | "
                f"{cat.mean_adjusted * 100:.1f}% | "
                f"{cat.mean_confidence * 100:.0f}% |"
            )
        lines.append("")

    # Classification breakdown
    total = max(stats.production_files, 1)
    lines += [
        "### Classification",
        "",
        f"| Label | Count | % |",
        f"|---|---|---|",
        f"| AI-like | {stats.ai_like_count} | {stats.ai_like_count/total*100:.1f}% |",
        f"| Mixed | {stats.mixed_count} | {stats.mixed_count/total*100:.1f}% |",
        f"| Human-like | {stats.human_like_count} | {stats.human_like_count/total*100:.1f}% |",
        f"| Uncertain | {stats.uncertain_count} | {stats.uncertain_count/total*100:.1f}% |",
        f"",
    ]

    # Module heatmap
    if stats.module_summaries:
        lines += [
            "### Module Heatmap (top modules by adjusted score)",
            "",
            "| Module | Files | Adj. Score | Risk | Languages |",
            "|---|---|---|---|---|",
        ]
        for mod in stats.module_summaries[:10]:
            emoji_m = _score_emoji(mod.mean_adjusted)
            langs = ", ".join(mod.languages[:3])
            lines.append(
                f"| `{mod.module_path}` | {mod.file_count} | "
                f"{emoji_m} {mod.mean_adjusted * 100:.1f}% | "
                f"{mod.mean_risk * 100:.1f}% | {langs} |"
            )
        lines.append("")

    # High-risk files
    if stats.top_risk_files:
        lines += [
            "### High-Risk Files — Review Candidates",
            "",
            "> Files ranked by engineering review priority (risk_score), "
            "not solely by AI-like signal.",
            "",
            "| File | Category | Adj. Score | Risk | Confidence | Recommendation |",
            "|---|---|---|---|---|---|",
        ]
        for a in stats.top_risk_files[:10]:
            rel = Path(a.path).name
            lines.append(
                f"| `{rel}` | {a.category.value} | "
                f"{a.adjusted_score*100:.1f}% | "
                f"{a.risk_score*100:.1f}% | "
                f"{a.confidence:.2f} | "
                f"{a.review_recommendation} |"
            )
        lines.append("")

    # Git signals
    if stats.git_signals:
        lines += [
            "### Git Pattern Signals",
            "",
            "| Signal | Value |",
            "|---|---|",
        ]
        for k, v in stats.git_signals.items():
            bar = _score_bar(v, width=10)
            lines.append(f"| {k} | {v:.2f} `{bar}` |")
        lines.append("")

    # Exclusions transparency
    if stats.exclusions:
        lines += [
            "### Exclusions (transparency)",
            "",
            f"- Generated files excluded from KPI: **{stats.exclusions.get('generated_excluded', 0)}**",
            f"- Vendor files excluded: **{stats.exclusions.get('vendor_excluded', 0)}**",
            f"- Example files excluded: **{stats.exclusions.get('example_excluded', 0)}**",
            f"- KPI-eligible files: **{stats.exclusions.get('kpi_eligible', 0)}**",
            "",
        ]

    # Review checklist
    checklist = _generate_review_checklist(stats, analyses)
    if checklist:
        lines += ["### Review Checklist", ""]
        lines += checklist
        lines.append("")

    # Known limitations
    lines += [
        "### Limitations & Uncertainty",
        "",
        "- Scores reflect code style patterns — **not** verified AI origin",
        "- High scores may result from: senior clean code, strict formatters, "
        "framework boilerplate, DTOs, generated clients, refactoring",
        "- Low scores do NOT rule out AI-assisted development",
        "- Generated, vendor, and example files are excluded from KPI by default",
    ]

    return lines


def _generate_review_checklist(stats: RepoStats, analyses: List[FileAnalysis]) -> List[str]:
    """Generate a review checklist from findings in high-risk files."""
    items = set()

    for a in stats.top_risk_files:
        for finding in a.findings:
            if finding.severity in ("high", "moderate"):
                items.add(f"- [ ] Review `{finding.rule_id}`: {finding.description}")

    # Add standard checklist items for high-risk files
    if stats.high_risk_count > 0:
        items.add("- [ ] Verify exception handling in high-risk production files")
        items.add("- [ ] Check transaction boundaries in service layer methods")
        items.add("- [ ] Confirm edge case coverage in critical business logic tests")
        items.add("- [ ] Review observability: structured logging and correlation IDs")

    return sorted(items)[:15]  # cap at 15 items


def build_pr_comment(
    repo_name: str,
    stats: RepoStats,
    baseline_kpi: Optional[float] = None,
) -> str:
    """Build a compact GitHub/GitLab PR comment."""
    emoji = _score_emoji(stats.kpi_score)
    delta = ""
    if baseline_kpi is not None:
        diff = stats.kpi_score - baseline_kpi
        delta = f" (Δ {diff:+.1%})"

    lines = [
        f"## {emoji} AI Pattern Analyzer Results",
        f"",
        f"**Repository:** `{repo_name}`  ",
        f"**KPI Score:** {stats.kpi_score * 100:.1f}%{delta} — {stats.summary_label}  ",
        f"**High-risk files:** {stats.high_risk_count}  ",
        f"",
        DISCLAIMER_MD,
    ]

    if stats.top_risk_files:
        lines += ["", "**Top review candidates:**", ""]
        for a in stats.top_risk_files[:5]:
            lines.append(
                f"- `{Path(a.path).name}` "
                f"({a.category.value}, adj={a.adjusted_score:.2f}, "
                f"risk={a.risk_score:.2f})"
            )

    return "\n".join(lines)
